EBIvariation/eva-accession

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/SubmittedVariant.java
- eva-accession-pipeline/src/main/java/uk/ac/ebi/eva/accession/pipeline/io/AccessionWriter.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/io/AccessionWriterTest.java
first part of the ticket, don't move to done after merging this.
> EVA-1204 Post-accessioning validation checks (1/2)

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/configuration/MongoConfiguration.java
- eva-accession-pipeline/src/main/resources/application.properties
- eva-accession-pipeline/src/test/resources/accession-pipeline-test.properties
- eva-accession-ws/pom.xml
- eva-accession-ws/src/main/java/uk/ac/ebi/eva/accession/ws/configuration/ApplicationConfiguration.java
- eva-accession-ws/src/main/java/uk/ac/ebi/eva/accession/ws/rest/SubmittedVariantsRestController.java
- eva-accession-ws/src/main/resources/application.properties
- eva-accession-ws/src/test/resources/accession-ws-test.properties
- pom.xml
merge this PR after https://github.com/EBIvariation/configuration/pull/14
I checked and this works on top of https://github.com/EBIvariation/eva-accession/pull/21 with just a small conflict, so https://github.com/EBIvariation/eva-accession/pull/22 can be merged before https://github.com/EBIvariation/eva-accession/pull/21 .
> EVA-1249 Deploy accessioning pipeline and WS to production

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/ClusteredVariant.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/IClusteredVariant.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/ISubmittedVariant.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/summary/DbsnpClusteredVariantSummaryFunction.java
- eva-accession-core/src/test/java/uk/ac/ebi/eva/accession/core/summary/DbsnpClusteredVariantSummaryFunctionTest.java
- eva-accession-core/src/test/java/uk/ac/ebi/eva/accession/core/summary/DbsnpSubmittedVariantSummaryFunctionTest.java
- eva-accession-core/src/test/java/uk/ac/ebi/eva/accession/core/summary/SubmittedVariantSummaryFunctionTest.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/io/DbsnpClusteredVariantWriter.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/persistence/DbsnpClusteredVariantEntity.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/io/DbsnpClusteredVariantWriterTest.java
this is only the writer for RSs. the writer that will be used in the import pipeline has to combine both this and the ss one.
> EVA-1265 Store RefSNP information in accessioning service

- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/model/DbsnpVariantAlleles.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/model/SubSnpNoHgvs.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/processors/AssemblyCheckerProcessor.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/model/DbsnpVariantAllelesTest.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/processors/SubSnpNoHgvsToSubmittedVariantProcessorTest.java
- Extracted the code to process the alleles from SubSnpNoHgvs t a new class DbSnpVariantAlleles
> EVA-1278 Map SS from dbSNP to Java model

- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/processors/SubSnpNoHgvsToDbsnpVariantsWrapperProcessor.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/processors/SubSnpNoHgvsToDbsnpVariantsWrapperProcessorTest.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/processors/SubmittedVariantRenormalizationProcessorTest.java
Decluster when SS and RS types differ
> EVA-1281 Decluster when SS and RS types differ

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/DbsnpClusteredVariantInactiveEntity.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/SubmittedVariantInactiveEntity.java
Added some indexes to be created in background mode.
> EVA-1336 Create all indexes in the accessioning service in the background

- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/io/AccessionedVariantMongoReader.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/io/VariantContextWriter.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/steps/processors/VariantToVariantContextProcessor.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/configuration/CreateReleaseStepConfigurationTest.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/io/AccessionedVariantMongoReaderTest.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/io/VariantContextWriterTest.java
- eva-accession-release/src/test/resources/test-data/dbsnpSubmittedVariantEntity.json
note that all flags are of type Flag (no value) except SS_VALIDATED which is of type Integer
> EVA-1363 Add flags to VCF report

- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/configuration/BeanNames.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/configuration/ImportDbsnpVariantsJobConfiguration.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/configuration/ListenersConfiguration.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/configuration/ValidateContigsProcessorConfiguration.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/configuration/ValidateContigsReaderConfiguration.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/configuration/ValidateContigsStepConfiguration.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/io/SubSnpNoHgvsContigReader.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/io/SubSnpNoHgvsContigRowMapper.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/processors/ContigSynonymValidationProcessor.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/configuration/ValidateContigsStepConfigurationFailingTest.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/configuration/ValidateContigsStepConfigurationTest.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/io/SubSnpNoHgvsContigReaderTest.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/processors/ContigSynonymValidationProcessorTest.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/test/BatchTestConfiguration.java
- eva-accession-import/src/test/resources/input-files/assembly-report/Gallus_gallus-4.0_test_assembly_report.txt
- eva-accession-import/src/test/resources/validate-contigs.properties
Query all contigs from dbSNP database
> EVA-1430 Abort import if a contig is not found in the assembly report

- eva-accession-import-automation/create_fasta_from_assembly_report.sh
most embarrassing bug in this repo
> EVA-1436 Create custom FASTA: use the proper variable for assembly report

- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/steps/processors/VariantToVariantContextProcessor.java
- eva-accession-release/src/main/resources/application.properties
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/io/VariantContextWriterTest.java
> EVA-1468 Generate RS release files - first batch (general eva-acc-release improvements)

- eva-accession-import-automation/check_invalid_genbank_contig_association.py
- eva-accession-import-automation/create_fasta_from_assembly_report.sh
- eva-accession-import-automation/data_ops.py
- eva-accession-import-automation/generate_custom_assembly_report.py
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/processors/ContigReplacerProcessor.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/configuration/ImportDbsnpVariantsStepConfigurationTest.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/processors/ContigReplacerProcessorTest.java
check_invalid_genbank_contig_association.py - Assess the impact of the bug on the species that have been imported thus far.
ContigReplacerProcessor.java, ContigReplacerProcessorTest.java, ImportDbsnpVariantsStepConfigurationTest.java - Updated pipeline code for future imports
> EVA-1523 - Assess and remediate invalid Genbank contig association

- eva-accession-import-automation/generate_custom_assembly_report.py
- eva-accession-import-automation/run_accession_import.py
- eva-accession-import-automation/run_accession_import_jobs.py
This is not exactly needed for chimpanzee but helps debugging issues with any species
> EVA-1502 Import chimpanzee_9598 into accessioning service

- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/io/VariantContextWriter.java
fix the metadata definition of SS_VALIDATED
> EVA-1553 Include INFO fields description in README file

- eva-accession-release/src/main/resources/copy_release_to_ftp.sh
Count unmapped RS IDs while copying the release to the ftp. Also copy the file with the counts for the rest of the files
> EVA-1555 Summary counts per species

- eva-accession-release/src/main/resources/__init__.py
- eva-accession-release/src/main/resources/validate_rs_release_files.py
Validate the RS release files. 
Basically attribute against the reasons that a RS won't show up in the release files:
* Merged SS parent
* Declustered SS parent
* Non-nucleotide letters
* STR type
> EVA-1657 - Validate RS release files

- eva-accession-release/src/main/resources/README_general_info.txt
Note: Look at only the second commit for the relevant changes. The file was a bit outdated.
> EVA-1723 Modify README in species folder to describe structure of folders

- eva-accession-release/src/main/resources/copy_release_to_ftp.sh
Updated the driver script in the cluster as well
> EVA-1680 - Updated script to accept FTP user as an argument

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/ClusteredVariantAccessioningService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/human/dbsnp/HumanDbsnpClusteredVariantAccessioningService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/human/dbsnp/HumanDbsnpClusteredVariantOperationAccessioningService.java
- eva-accession-core/src/test/java/uk/ac/ebi/eva/accession/core/service/human/dbsnp/HumanDbsnpClusteredVariantAccessioningServiceTest.java
- eva-accession-ws/src/main/java/uk/ac/ebi/eva/accession/ws/rest/ClusteredVariantsRestController.java
- eva-accession-ws/src/main/java/uk/ac/ebi/eva/accession/ws/service/ClusteredVariantsBeaconService.java
- eva-accession-ws/src/test/java/uk/ac/ebi/eva/accession/ws/ClusteredVariantsRestControllerTest.java
Return MODELS in the `core` module and convert them to DTOs in the `ws` module
> EVA-1745 Return models in core module

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/GetOrCreateAccessionWrapperCreator.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/nonhuman/SubmittedVariantAccessioningService.java
- eva-accession-core/src/test/java/uk/ac/ebi/eva/accession/core/service/nonhuman/SubmittedVariantAccessioningServiceTest.java
- eva-accession-pipeline/src/main/java/uk/ac/ebi/eva/accession/pipeline/batch/io/AccessionReportWriter.java
- eva-accession-pipeline/src/main/java/uk/ac/ebi/eva/accession/pipeline/batch/io/AccessionWriter.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/batch/io/AccessionReportWriterTest.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/batch/io/AccessionWriterTest.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/batch/io/GetOrCreateAccessionWrapperCreator.java
- eva-accession-ws/src/test/java/uk/ac/ebi/eva/accession/ws/SubmittedVariantsRestControllerTest.java
- pom.xml
Support accession commons 0.6.4
> EVA-1792 - Support accession commons 0.6.4

- eva-accession-pipeline/src/main/resources/monitoring/__init__.py
- eva-accession-pipeline/src/main/resources/monitoring/monitor_duplicate_accessions.py
monitor_duplicate_accessions.py - Given a collection name and database properties file, export accessions to a file and identify duplicates.
> EVA-1818 - Monitor duplicate accessions in MongoDB

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/configuration/nonhuman/ClusteredVariantAccessioningConfiguration.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/nonhuman/dbsnp/DbsnpSubmittedVariantAccessioningDatabaseService.java
- eva-accession-ws/src/test/java/uk/ac/ebi/eva/accession/ws/SubmittedVariantsRestControllerTest.java
Fixed endpoint [hosted here](https://wwwdev.ebi.ac.uk/eva/webservices/identifiers/EVA-1841/v1/submitted-variants/1)
> EVA-1841 - Use HTTP 404 for non-existent submitted variants

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/repository/nonhuman/eva/ClusteredVariantAccessioningRepository.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/repository/nonhuman/eva/ClusteredVariantAccessioningRepositoryImpl.java
- eva-accession-core/src/test/java/uk/ac/ebi/eva/accession/core/repository/nonhuman/eva/ClusteredVariantAccessioningRepositoryTest.java
Fixed criteria bug in ClusteredVariantAccessioningRepository and added tests
> EVA-1793 - Spring Boot 2 upgrade - fix criteria bug in ClusteredVariantAccessioningRepository 

- eva-accession-release-automation/analyze_mapping_weight_impact/__init__.py
- eva-accession-release-automation/analyze_mapping_weight_impact/construct_asm_lookup_table.py
- eva-accession-release-automation/analyze_mapping_weight_impact/construct_snpmapinfo_schema_bank.py
- eva-accession-release-automation/analyze_mapping_weight_impact/create_snpmapinfo_indexes.py
- eva-accession-release-automation/analyze_mapping_weight_impact/dbsnp_mirror_metadata.py
- eva-accession-release-automation/analyze_mapping_weight_impact/import_missing_snpmapinfo_tables.py
- eva-accession-release-automation/analyze_mapping_weight_impact/lookup_overweight_snps_in_release_files.py
- eva-accession-release-automation/analyze_mapping_weight_impact/remove_snpmapinfo_table_name_suffixes.py
- eva-accession-release-automation/analyze_mapping_weight_impact/snpmapinfo_metadata.py
Usage of the individual scripts documented in the comments in https://www.ebi.ac.uk/panda/jira/browse/EVA-2015. 
The scripts are unlikely to be reused so the usual coding standards were not rigorously adhered to :D
> EVA-2015 - Scripts to prepare SNPMapInfo table and lookup overweight SNPs in release files

- eva-accession-deprecate/src/main/resources/application.properties
- eva-accession-import-dbsnp2/src/main/java/uk/ac/ebi/eva/accession/dbsnp2/configuration/RunnerConfiguration.java
- eva-accession-import-dbsnp2/src/main/resources/application.properties
- eva-accession-import/src/main/resources/application.properties
- eva-accession-pipeline/src/main/resources/application.properties
- eva-accession-release/src/main/resources/application.properties
- Additional property to work around [CLOB message](https://github.com/pgjdbc/pgjdbc/issues/1102) during pipeline run
- Missing runner bean for human import pipeline
> EVA-2019 - MongoDB 4 test run issues

- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/ClusteringWriter.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/repository/nonhuman/dbsnp/DbsnpSubmittedVariantAccessioningRepository.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/repository/nonhuman/eva/SubmittedVariantAccessioningRepository.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/nonhuman/ClusteredVariantAccessioningService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/nonhuman/SubmittedVariantAccessioningService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/nonhuman/dbsnp/DbsnpClusteredVariantAccessioningDatabaseService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/nonhuman/dbsnp/DbsnpClusteredVariantMonotonicAccessioningService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/nonhuman/dbsnp/DbsnpSubmittedVariantAccessioningDatabaseService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/nonhuman/dbsnp/DbsnpSubmittedVariantMonotonicAccessioningService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/nonhuman/eva/ClusteredVariantAccessioningDatabaseService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/nonhuman/eva/ClusteredVariantMonotonicAccessioningService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/nonhuman/eva/SubmittedVariantAccessioningDatabaseService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/nonhuman/eva/SubmittedVariantMonotonicAccessioningService.java
- eva-accession-core/src/test/java/uk/ac/ebi/eva/accession/core/service/nonhuman/ClusteredVariantAccessioningServiceTest.java
- eva-accession-core/src/test/java/uk/ac/ebi/eva/accession/core/service/nonhuman/SubmittedVariantAccessioningServiceTest.java
- eva-accession-ws/src/main/java/uk/ac/ebi/eva/accession/ws/rest/ClusteredVariantsRestController.java
- eva-accession-ws/src/main/java/uk/ac/ebi/eva/accession/ws/rest/SubmittedVariantsRestController.java
- eva-accession-ws/src/main/java/uk/ac/ebi/eva/accession/ws/service/ClusteredVariantsBeaconService.java
- eva-accession-ws/src/main/java/uk/ac/ebi/eva/accession/ws/service/SubmittedVariantsBeaconService.java
- eva-accession-ws/src/test/java/uk/ac/ebi/eva/accession/ws/ClusteredVariantsRestControllerTest.java
- eva-accession-ws/src/test/java/uk/ac/ebi/eva/accession/ws/SubmittedVariantsRestControllerTest.java
- pom.xml
Merge EBIVariation/variation-commons#96 before this PR
> EVA-2033 Refactor eva accession

- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/ClusteringWriter.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/listeners/ClusteringCounts.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/listeners/ClusteringProgressListener.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/ClusteringAssertions.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/IssueAccessionClusteringWriterTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/MergeAccessionClusteringWriterTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/ReuseAccessionClusteringWriterTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/jobs/ClusteringVariantJobConfigurationTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/steps/ClusteringVariantStepConfigurationTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/runner/ClusteringCommandLineRunnerTest.java
- eva-accession-clustering/src/test/resources/test-data/clusteredVariantEntityForVcfJob.json
don't merge this PR until #228 is merged. This PR will need some extra changes on top of that.
> EVA-2071 Don't cluster submitted variants into multimap clustered variants

- eva-accession-release-automation/include_mapping_weight_from_dbsnp/export_all_multimap_snps_from_dbsnp_dumps.py
- eva-accession-release-automation/include_mapping_weight_from_dbsnp/requirements.txt
- eva-accession-release-automation/include_mapping_weight_from_dbsnp/validate_mapping_weight_addition_to_mongo.py
See [here](https://www.ebi.ac.uk/panda/jira/browse/EVA-2086?focusedCommentId=335503&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-335503)
> EVA-2086 - Validation scripts to check map weight attribute addition

- eva-accession-import-automation/genome_downloader.py
- eva-accession-import-automation/requirements.txt
Uses `NCBIAssembly` added in https://github.com/EBIvariation/eva-common-pyutils/pull/8
> EVA-2132 genome downloader

- eva-accession-pipeline/pom.xml
- eva-accession-pipeline/src/main/java/uk/ac/ebi/eva/accession/pipeline/configuration/EvaAccessionPipelineBatchConfigurer.java
See https://stackoverflow.com/a/58707589
> Overridde BatchConfigurer to be backwards compatible with Spring Boot 1 job repository

- .gitlab-ci.yml
When renaming the remapping modules the gitlab CI pipeline was not updated
> Change remapping module name in gitlab CI pipeline

- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/batch/io/RemappedSubmittedVariantsWriter.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/batch/listeners/RemappingIngestCounts.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/batch/listeners/RemappingIngestionProgressListener.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/configuration/BeanNames.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/configuration/batch/io/IngestRemappedSubmittedVariantsWriterConfiguration.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/configuration/batch/listeners/ListenerConfiguration.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/configuration/batch/steps/IngestRemappedFromVcfStepConfiguration.java
- eva-remapping-ingest/src/main/resources/application.properties
- eva-remapping-ingest/src/test/java/uk/ac/ebi/eva/remapping/ingest/configuration/batch/jobs/IngestRemappedVariantsFromVcfJobConfigurationTest.java
- eva-remapping-ingest/src/test/java/uk/ac/ebi/eva/remapping/ingest/test/configuration/BatchTestConfiguration.java
- eva-remapping-ingest/src/test/resources/ingest-remapped-variants.properties
- eva-remapping-ingest/src/test/resources/logback.xml
> EVA-2420 Improve remapped variants ingestion pipeline

- eva-remapping-get-source/src/main/java/uk/ac/ebi/eva/remapping/source/batch/io/DbsnpSubmittedVariantMongoReader.java
- eva-remapping-get-source/src/main/java/uk/ac/ebi/eva/remapping/source/batch/io/EvaSubmittedVariantMongoReader.java
- eva-remapping-get-source/src/main/java/uk/ac/ebi/eva/remapping/source/batch/io/VariantContextWriter.java
- eva-remapping-get-source/src/main/java/uk/ac/ebi/eva/remapping/source/batch/processors/SubmittedVariantToVariantContextProcessor.java
- eva-remapping-get-source/src/main/java/uk/ac/ebi/eva/remapping/source/configuration/batch/io/SubmittedVariantMongoReaderConfiguration.java
- eva-remapping-get-source/src/main/java/uk/ac/ebi/eva/remapping/source/parameters/InputParameters.java
- eva-remapping-get-source/src/main/resources/application.properties
- eva-remapping-get-source/src/test/java/uk/ac/ebi/eva/remapping/source/batch/io/DbsnpSubmittedVariantMongoReaderTest.java
- eva-remapping-get-source/src/test/java/uk/ac/ebi/eva/remapping/source/batch/io/EvaSubmittedVariantMongoReaderTest.java
- eva-remapping-get-source/src/test/java/uk/ac/ebi/eva/remapping/source/batch/io/VariantContextWriterTest.java
- eva-remapping-get-source/src/test/java/uk/ac/ebi/eva/remapping/source/batch/processors/VariantToVariantContextProcessorTest.java
- eva-remapping-get-source/src/test/java/uk/ac/ebi/eva/remapping/source/configuration/batch/jobs/ExportSubmittedVariantsJobConfigurationTest.java
- eva-remapping-get-source/src/test/java/uk/ac/ebi/eva/remapping/source/runner/AccessionRemappingJobLauncherCommandLineRunnerTest.java
- eva-remapping-get-source/src/test/java/uk/ac/ebi/eva/remapping/source/runner/AccessionRemappingJobLauncherCommandLineRunnerWithProjectsTest.java
- eva-remapping-get-source/src/test/resources/test-data/dbsnpSubmittedVariantEntity.json
- eva-remapping-get-source/src/test/resources/test-data/submittedVariantEntity.json
- eva-remapping-get-source/src/test/resources/with-projects.properties
> EVA-2440 Improve remapping extractor

- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/MergeAccessionClusteringWriterTest.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/model/eva/SubmittedVariantEntity.java
- eva-accession-core/src/test/java/uk/ac/ebi/eva/accession/core/service/nonhuman/SubmittedVariantAccessioningServiceTest.java
- eva-remapping-ingest/pom.xml
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/batch/processors/VariantToSubmittedVariantEntityRemappedProcessor.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/batch/tasklets/RemappingMetadata.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/batch/tasklets/RemappingMetadataSummaryFunction.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/batch/tasklets/StoreRemappingMetadataTasklet.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/configuration/BeanNames.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/configuration/RemappingMetadataConfiguration.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/configuration/batch/jobs/IngestRemappedVariantsFromVcfJobConfiguration.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/configuration/batch/processors/VariantProcessorConfiguration.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/configuration/batch/steps/StoreRemappingMetadataStepConfiguration.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/parameters/InputParameters.java
- eva-remapping-ingest/src/main/resources/application.properties
- eva-remapping-ingest/src/test/java/uk/ac/ebi/eva/remapping/ingest/configuration/batch/jobs/IngestRemappedVariantsFromVcfJobConfigurationTest.java
- eva-remapping-ingest/src/test/java/uk/ac/ebi/eva/remapping/ingest/test/configuration/BatchTestConfiguration.java
- eva-remapping-ingest/src/test/resources/ingest-remapped-variants-dbsnp.properties
- eva-remapping-ingest/src/test/resources/ingest-remapped-variants.properties
Should rebased and merged after PR #272
> EVA-2470 Remapping metadata

- eva-accession-pipeline/src/main/resources/utilities/replace_incorrect_contigs_in_accessioning_warehouse.py
- eva-accession-pipeline/src/main/resources/utilities/requirements.txt
- eva-accession-pipeline/src/main/resources/utilities/test/test_replace_incorrect_contigs.py
Parametrized [script](https://github.com/EBIvariation/eva-tasks/blob/master/tasks/eva_2464/correct_contig_error_in_study.py) which was in eva-tasks for EVA-2464.
Source diff [here](https://www.textcompare.org/python/?id=60dc9b7354b66f0014257f4d)
Test diff [here](https://www.textcompare.org/python?id=60dc9c8a54b66f0014257f56)
Usage [here](https://www.ebi.ac.uk/panda/jira/browse/EVA-2169?focusedCommentId=363804&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-363804)
> EVA-2169 - Create accessioning utility scripts

- eva-accession-clustering-automation/clustering_automation/create_clustering_progress_table.py
- eva-accession-clustering-automation/requirements.txt
Take the list of assembly from the remapping table (for the mapped variants) and from last year inventory table for the unmapped variants.
> EVA-2517 - New script to fill in the clustering/release progress table

- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/ClusteringMongoReader.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/io/ClusteringMongoReaderConfiguration.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/ClusteringMongoReaderTest.java
- eva-accession-clustering/src/test/resources/test-data/dbsnpSubmittedVariantEntityMongoReader.json
@apriltuesday @tcezard @nitin-ebi  This PR is on top of EVA-2565 PR. Therefore you will see a lot of commits. However, the only relevant commit for this PR is [this](https://github.com/EBIvariation/eva-accession/commit/afd5d08cfd0a945d24f8339d356f6ae48baf633d) and can be independently reviewed regardless of EVA-2565 PR.
> EVA-2595 - Use multiple SS readers

- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/RSMergeWriter.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/io/RSMergeAndSplitCandidatesReaderConfiguration.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/runner/ClusteringCommandLineRunnerTest.java
When processing a merge, [update upcoming merge candidates involving the mergee](https://docs.google.com/spreadsheets/d/1KQLVCUy-vqXKgkCDt2czX6kuMfsjfCc9uBsS19MZ6dY/edit#rangeid=1846669126) with the current target RS.
> EVA-2574 - Address overlapping merges

- eva-accession-clustering-automation/clustering_automation/cluster_from_mongo.py
so multiple process don't share the same nextflow work directory and logs
> EVA-2634 - Run the nextflow inside the assembly directory 

- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/ClusteringWriter.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/runner/ClusteringCommandLineRunnerTest.java
Usage [here](https://www.ebi.ac.uk/panda/jira/browse/EVA-2683?focusedCommentId=378189&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-378189)
> EVA-2683 - Make merge and split determination idempotent

- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/qc/PendingMergeSplitReporter.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/qc/RSReader.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/qc/SSReader.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/processors/qc/ReportUnclusteredSSProcessor.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/jobs/qc/ClusteringQCJobConfiguration.java
Commit descriptions below are self-explanatory
> EVA-2634 - Fix QC false positives

- eva-accession-release-automation/run_release_in_embassy/count_rs_ids_in_release_files.py
- eva-accession-release-automation/run_release_in_embassy/merge_dbsnp_eva_release_files.py
- eva-accession-release-automation/run_release_in_embassy/release_common_utils.py
- eva-accession-release-automation/run_release_in_embassy/run_release_for_species.py
- eva-accession-release-automation/run_release_in_embassy/sort_bgzip_index_release_files.py
- eva-accession-release-automation/run_release_in_embassy/update_sequence_names_to_ena.py
- eva-accession-release-automation/run_release_in_embassy/validate_release_vcf_files.py
Requires https://github.com/EBIvariation/contig_name_converter/pull/1
> Add process to update sequence name to use ENA convention

- eva-remapping-get-source/src/main/java/uk/ac/ebi/eva/remapping/source/batch/io/DbsnpSubmittedVariantMongoReader.java
- eva-remapping-get-source/src/main/java/uk/ac/ebi/eva/remapping/source/batch/io/EvaSubmittedVariantMongoReader.java
- eva-remapping-get-source/src/test/resources/test-data/submittedVariantEntity.json
Existing test shows that the new variant is not getting read.
> EVA-2991 - Do not export the variant that have already been remapped

- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/ClusteringWriter.java
See [here](https://ebi-eva.slack.com/archives/C5F1J0FK3/p1683188686204029) for context
> Use iterator instead of mongotemplate find to read merge/split candidates

- eva-accession-release-automation/gather_clustering_counts/gather_clustering_counts_from_mongo.py
@tcezard @nitin-ebi @apriltuesday  Only [this commit](https://github.com/EBIvariation/eva-accession/pull/406/commits/9ca358b46c0b78510c1542d883afdbcdc8d8495a) is to be reviewed since this PR is built on top of [this](https://github.com/EBIvariation/eva-accession/pull/404)
> EVA-3347 - Include deprecation counts

- eva-accession-release-automation/publish_release_to_ftp/publish_release_files_to_ftp.py
- eva-accession-release-automation/run_release_in_embassy/release_metadata.py
- eva-accession-release-automation/run_release_in_embassy/sort_bgzip_index_release_files.py
Ensure the general release info come from the cod
Create the symlinks in the  by_species/species/assembly folder
> EVA-3354 - fix Release readme location

- eva-accession-release-automation/run_release_in_embassy/run_release_for_assembly.py
- eva-accession-release-automation/run_release_in_embassy/run_release_for_species.py
- Fix resume option
- Fix mongodb port 
- Also Add a name to the workflow run to make it easier to identify in tower
> Fix release port

- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/ClusteringWriter.java
* Don't include unchanged operations in list of operations to update
* Change fetching of existing operations from aggregate to find
> EVA-3629: Updates to process remapped variants writer
