- pom.xml
- src/main/java/uk/ac/ebi/eva/accession/variant/VariantAccessioningConfiguration.java
- src/main/java/uk/ac/ebi/eva/accession/variant/persistence/VariantAccessioningDatabaseService.java
- src/main/resources/application.properties
- src/test/java/uk/ac/ebi/eva/test/configurationaccession/VariantAccessioningDatabaseServiceTestConfiguration.java
- src/test/resources/application.properties
PostgreSQL driver dependency added to POM file.
Spring Boot Maven plug-in configured to run Spring Boot application with `java -jar`.
Package imports accommodating changes in https://github.com/EBIvariation/accession-commons/pull/20
Copyright headers removed from properties files.
> EVA-1116 Fix to work on PostgreSQL and refactoring

- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/io/AccessionReportWriterTest.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/io/AccessionWriterTest.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/io/FastaSequenceReaderTest.java
- eva-accession-pipeline/src/test/resources/accession-pipeline-test.properties
Used toUri instead of getFile to get path File in order to support windows. 
Added windows temp path (commented) in accession-pipeline-test.properties, it must be used when running test in windows. 
Git property core.autocrlf must be set to input if using a windows machine so line ending will be LF instead of CRLF.
> Eva Accession Pipeline compatible with Windows

- .travis.yml
- eva-accession-core/pom.xml
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/SubmittedVariant.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/SubmittedVariantAccessioningService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/configuration/SubmittedVariantAccessioningConfiguration.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/SubmittedVariantAccessioningDatabaseService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/SubmittedVariantAccessioningRepositoryImpl.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/SubmittedVariantEntity.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/SubmittedVariantInactiveEntity.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/SubmittedVariantOperationEntity.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/SubmittedVariantOperationRepository.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/SubmittedVariantInactiveService.java
- eva-accession-core/src/test/java/uk/ac/ebi/eva/accession/core/SubmittedVariantAccessioningServiceTest.java
- eva-accession-core/src/test/java/uk/ac/ebi/eva/accession/core/test/configuration/MongoDbTestConfiguration.java
- eva-accession-core/src/test/java/uk/ac/ebi/eva/accession/core/test/configuration/MongoTestConfiguration.java
- eva-accession-core/src/test/java/uk/ac/ebi/eva/accession/core/test/rule/FixSpringMongoDbRule.java
- eva-accession-core/src/test/resources/accession-test.properties
- eva-accession-core/src/test/resources/ss-accession-test.properties
- eva-accession-import/pom.xml
- eva-accession-pipeline/pom.xml
- eva-accession-pipeline/src/main/java/uk/ac/ebi/eva/accession/pipeline/io/AccessionWriter.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/io/AccessionWriterTest.java
- eva-accession-ws/pom.xml
- eva-accession-ws/src/main/java/uk/ac/ebi/eva/accession/ws/rest/SubmittedVariantDTO.java
- eva-accession-ws/src/main/java/uk/ac/ebi/eva/accession/ws/rest/SubmittedVariantsRestController.java
- pom.xml
The new version of the dependency improves support for MongoDB, including the request of overlapping variants across files in the same study.
It also drops the 'active' and 'version' flags, which are now defined in an interface.
All the variants in the main collection are considered active, and those that have been merged or deprecated will go into a history collection. The list of operations performed over an accession will be tracked in said collection.
> EVA-1208 Upgrade dependency to accession-commons 0.4

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/SubmittedVariantModelSummaryFunction.java
- eva-accession-core/src/test/java/uk/ac/ebi/eva/accession/core/SubmittedVariantModelSummaryFunctionTest.java
The EVA groups variants based on the reference assembly they are mapped against. A species and its subspecies are considered under a single group, so the taxonomy needs to be removed from the summary function. dbSNP SubSNPs do take into account both.
> EVA-1208 EVA-1235 Fix submitted variant model summary function

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/configuration/MongoConfiguration.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/SubmittedVariantEntity.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/io/AccessionWriterTest.java
reduce documents from 372 to 227 bytes. this means that when we have 10 billion accessions, the size will be 2.27 TB instead of 3.72 TB. 
We could also change (in accession-commons):
- "createdDate" to "created"
- "version" to "ver"
but my measures show no difference (others' measures show 2 bytes which would be 20 GB, 0.88 %).
Note that I improved the test that checks the auto generated date
> EVA-1251 Reduce size of MongoDB documents

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/SubmittedVariantAccessioningService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/configuration/SubmittedVariantAccessioningConfiguration.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/DbSnpSubmittedVariantAccessioningRepositoryImpl.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/DbsnpMonotonicAccessionGenerator.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/DbsnpSubmittedVariantAccessioningDatabaseService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/DbsnpSubmittedVariantAccessioningRepository.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/DbsnpSubmittedVariantAccessioningRepositoryImpl.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/DbsnpSubmittedVariantEntity.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/DbsnpSubmittedVariantInactiveEntity.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/DbsnpSubmittedVariantOperationEntity.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/DbsnpSubmittedVariantOperationRepository.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/DbsnpSubmittedVariantInactiveService.java
- eva-accession-core/src/test/java/uk/ac/ebi/eva/accession/core/SubmittedVariantAccessioningServiceTest.java
- eva-accession-core/src/test/resources/ss-accession-test.properties
- eva-accession-core/src/test/resources/test-data/dbsnpSubmittedVariantEntity.json
- eva-accession-core/src/test/resources/test-data/submittedVariantEntity.json
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/io/DbsnpSubmittedVariantWriter.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/processors/SubSnpNoHgvsToVariantProcessor.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/io/DbsnpSubmittedVariantWriterTest.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/processors/SubSnpNoHgvsToVariantProcessorTest.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/io/AccessionWriterTest.java
- eva-accession-pipeline/src/test/resources/accession-pipeline-test.properties
- eva-accession-ws/src/test/resources/accession-ws-test.properties
Created Dbsnp entity, repository, database service. Modified service `SubmittedVariantAccessioningService` to use both repositories. Added tests.
> EVA-1182 Access to legacy dbSNP SS objects with coordinates

- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/model/DbsnpVariantAlleles.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/model/DbsnpVariantAllelesTest.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/processors/SubSnpNoHgvsToDbsnpVariantsWrapperProcessorTest.java
Microsatellite alleles can be expressed in different formats, some of which are compressed. This PR unrolls these compressed alleles, ensuring that they are compatible with VCF and the rest of our systems.
Examples:
`(T)4` becomes `TTTT`
`AG(T)4(ACT)3(C)5` becomes `AGTTTTACTACTACTCCCCC`
> EVA-1278 Unroll compressed microsatellite alleles

- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/processors/AssemblyCheckerProcessor.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/processors/AssemblyCheckerProcessorTest.java
Report differently assembly check fails due to sequence not found or coordinates too large. The 'alleles mismatch' flag is appropriately set, instead of throwing an exception and making the pipeline fail.
> EVA-1296 Improve reporting of assembly check errors

- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/configuration/ImportDbsnpVariantsWriterConfiguration.java
The `MongoConfiguration` class exposes a `MongoTemplate` bean that doesn't store a `_class` field in MongoDB. This was automatically configured in the module eva-accession-pipeline through the accessioning service configuration, but because eva-accession-import uses a plain Spring Batch writer, this configuration wasn't present.
Injecting this configuration into the appropriate writer solves the problem. The only limitation the lack of this field imposes is that polymorphism is not possible, but it is not a concern in our case.
> EVA-1296 Do not store Spring Data _class field

- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/model/SubSnpNoHgvs.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/processors/SubSnpNoHgvsToDbsnpVariantsWrapperProcessor.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/processors/SubSnpNoHgvsToDbsnpVariantsWrapperProcessorTest.java
we forgot one place where the unknown orientation was producing unexpected behaviour. This PR makes the code:
- assume FORWARD **always** that there's an unknown orientation.
- flag a subsnp as alleles mismatch if there was at least one unknown orientation (or if the reference allele was not found in the list of alleles, which was the only reason to use this flag before).
> EVA-1287 Pilot for import into accessioning service - corner cases (unknown orientation again)

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/DbsnpClusteredVariantAccessioningDatabaseService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/DbsnpSubmittedVariantAccessioningDatabaseService.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/SubmittedVariantAccessioningDatabaseService.java
- pom.xml
- Updated to accession commons 0.5.2
- Used `BasicSpringDataRepositoryMonotonicDatabaseService` instead of `BasicSpringDataRepositoryDatabaseService`
> EVA-1373 Re initialization of blocks at application start

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/persistence/SubmittedVariantEntity.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/io/DbsnpVariantsWriter.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/processors/SubmittedVariantDeclusterProcessor.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/io/DbsnpVariantsWriterTest.java
If an RS (for instance rs1) is merged into another RS (for instance rs2), update SSs (in rs1) to point to the active RS (rs2), and add an update in the SubmittedVariantOperation collection with the old RS.
If the RS was merged into several RSs (for instance, the pipeline merges  [rs193927678](https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=193927678) into [rs1095750933 ](https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=1095750933 ) and [rs347458720](https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=347458720)), update each SS with the corresponding RS, and put the operation for each SS (even if the old RS is the same).
> EVA-1310 Import arabidopsis_3702 into accessioning

- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/processors/SubSnpNoHgvsToClusteredVariantProcessor.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/processors/SubSnpNoHgvsToDbsnpVariantsWrapperProcessor.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/processors/SubSnpNoHgvsToDbsnpVariantsWrapperProcessorTest.java
A NullPointerException was raised when any of the creation dates were null. This has been corrected and relevant tests added.
> EVA-1322 Created date appropriately set when available on SS, RS or none

- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/io/DbsnpClusteredVariantDeclusteredWriter.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/io/DbsnpClusteredVariantWriter.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/io/DbsnpVariantsWriter.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/io/DbsnpClusteredVariantDeclusteredWriterTest.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/io/DbsnpVariantsWriterTest.java
rs638662487  should be declustered but makes collision in the declustered collection, so it also has to be written in the operations collection as a merge.
> EVA-1320 Import goat_9925 into accessioning service

- eva-accession-release/pom.xml
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/configuration/AccessionedVariantMongoReaderConfiguration.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/configuration/BeanNames.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/configuration/InputParametersConfiguration.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/configuration/ListenersConfiguration.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/io/AccessionedVariantMongoReader.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/parameters/InputParameters.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/io/AccessionedVariantMongoReaderTest.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/test/configuration/MongoTestConfiguration.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/test/rule/FixSpringMongoDbRule.java
- eva-accession-release/src/test/resources/accession-release-test.properties
- eva-accession-release/src/test/resources/test-data/dbsnpClusteredVariantEntity.json
- eva-accession-release/src/test/resources/test-data/dbsnpSubmittedVariantEntity.json
Perform the aggregation (with the `$lookup`) to query clustered variants.
**Note**: In another ticket, we need to do a processor to exclude clustered variants that don't have any submitted variants.
The raw MongoDB java driver was used, as our version of Spring Data MongoDB returned the results in a list, not in a cursor. Newer versions of Spring Data MongoDB have what we want, but we would have to migrate to Spring Boot 2.
> EVA-1358 Get list of variants in an assembly

- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/steps/processors/ExcludeInvalidVariantsProcessor.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/steps/processors/ExcludeInvalidVariantsProcessorTest.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/steps/processors/VariantToVariantContextProcessorTest.java
There was an impossible cycle where ExcludeInvalidVariantsProcessor complained
if the alleles were empty, but the ContextNucleotideAdditionProcessor is
put afterwards, to avoid adding nucleotides to alleles with strange characters.
we can remove the check from ExcludeInvalidVariantsProcessor because the
VariantToVariantContextProcessor is after the other processors and also
checks for empty alleles
> EVA-1362 Write output VCF report (indels bug)

- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/deciders/ForceImportDecider.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/parameters/InputParameters.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/configuration/ImportDbsnpVariantsJobConfigurationFailValidationStepTest.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/configuration/ImportDbsnpVariantsJobConfigurationTest.java
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/runner/DbsnpImportVariantsJobLauncherCommandLineRunnerTest.java
- eva-accession-import/src/test/resources/validate-contigs.properties
Pipeline was failing if `forceImport` parameter was not set in the properties file.
The type for the input parameter `forceImport` was changed from String to boolean, default value will be false.
> EVA-1432 Fix problem when not passing forceImport parameter

- eva-accession-import-automation/create_fasta_from_assembly_report.sh
Given an assembly report, download the FASTA sequence for all the GenBank accessions listed in it, and build a FASTA file that should cover all those present in the dbSNP database.
This script only works for RefSeq sequences which have GenBank equivalents. It is not possible to download RefSeq-only sequences from ENA, and there is no easy way to retrieve them from NCBI either :disappointed:
> EVA-1436 Prepare FASTA file with all INSDC sequences in an assembly report

- eva-accession-import-automation/README.md
- eva-accession-import-automation/data_ops.py
- eva-accession-import-automation/generate_custom_assembly_report.py
- eva-accession-import-automation/generate_properties.py
- eva-accession-import-automation/requirements.txt
Unfortunately, most of the parameters are the databases connection credentials, but if the program finishes, the properties file (`<assembly_accession>.properties`) should be usable for the import job.
I can add another parameter for the output filename, instead of `<assembly_accession>.properties` if you think it will be easier to integrate.
> EVA-1437 Populate properties file with provided parameters

- eva-accession-import-automation/create_fasta_from_assembly_report.sh
When the ENA API does not return any results, the line count will be zero.
The previous code would still try to write to the FASTA file, then display a misleading message when `grep` couldn't find the string.
> EVA-1436 Only write to FASTA file if more than 1 line is downloaded

- eva-accession-import-automation/create_fasta_from_assembly_report.sh
By checking if a sequence is already in the FASTA file before writing to it, we make sure there won't be any duplicates. Otherwise the FASTA can't be indexed.
Temporary contig files are also now written to the output folder, instead of the one the script is run from!
> EVA-1436 Prevent duplicate sequences in the output FASTA 

- .travis.yml
- eva-accession-import-automation/generate_custom_assembly_report.py
- eva-accession-import-automation/tests/test_generate_custom_assembly_report.py
This PR still uses the genbank equivalent text file from the EBI cluster file system instead of a database table since the memory usage was not prohibitive (around 1GB - and this will be run as a bsub job in conjunction with the main java pipeline which will need more than that anyway)
> EVA-1433 - Use full genbank equivalents file instead of just assembly related ones

- eva-accession-import-automation/create_fasta_from_assembly_report.sh
with a previous versions I found a silent error where a contig was downloaded partially. I expect wget returns an error exit code in that case.
**Note**: if a contig is not available at all, I kept the behaviour of logging it and continue. the script only stops if there was something downloaded and wget returned non-zero exit code
> EVA-1436 create FASTA: add retry logic for wget

- eva-accession-import-automation/create_fasta_from_assembly_report.sh
The ENA API feature about redirecting to the FTP when retrieving a contig that belongs to a WGS sequence is still not deployed in production. Once it is the URL must be changed to use `www` instead of `wwwdev`
> EVA-1436 Include WGS sequences in FASTA

- eva-accession-import-automation/create_fasta_from_assembly_report.sh
It was failing when the path of the output folder was not where the script was being run
> EVA-1436 Fix grep pointing to the correct path

- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/processors/ContigReplacerProcessor.java
Log only once per contig when a contig and a chromosome are not in the same line of the assembly report
> EVA-1458 Log message only once per contig

- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/processors/AssemblyCheckerProcessor.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/processors/SubmittedVariantRenormalizationProcessor.java
`Contig not found in FASTA` messages are logged in the `assembly checker` processor and `renormalization` processor
> EVA-1458 Aggregate log messages (contig not found in FASTA file)

- eva-accession-import-automation/data_ops.py
- eva-accession-import-unmapped/generate-unmapped-variants-report.py
* data_ops.py - Provisions to use custom base table to get species information - see [here](https://www.ebi.ac.uk/panda/jira/browse/EVA-1460?focusedCommentId=272237&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-272237)
* generate-unmapped-variants-report.py - 
- Create dummy ContigLoc tables for species that don't have it
- Aggregate flanking sequence lines in SubSNPSeq tables into a single string
> EVA-1460 - Aggregate SubSNPSeq table lines + dummy contigloc tables for species

- eva-accession-import-automation/create_fasta_from_assembly_report.sh
- eva-accession-import-automation/run_accession_import.py
create_fasta_from_assembly_report.sh - Invoke EUtils Entrez endpoint to get NCBI FASTA when ENA FASTA fetch fails
run_accession_import.py - Supply EUtils API key to the "create fasta" script
> EVA-1384 - Use NCBI FASTA as the last resort when ENA FASTA is missing

- eva-accession-deprecate/src/main/java/uk/ac/ebi/eva/accession/deprecate/configuration/DeprecableClusteredVariantsReaderConfiguration.java
- eva-accession-deprecate/src/main/java/uk/ac/ebi/eva/accession/deprecate/io/DeprecableClusteredVariantsReader.java
- eva-accession-deprecate/src/main/java/uk/ac/ebi/eva/accession/deprecate/io/DeprecationWriter.java
- eva-accession-deprecate/src/main/resources/application.properties
- eva-accession-deprecate/src/test/java/uk/ac/ebi/eva/accession/deprecate/configuration/DeprecateClusteredVariantsJobConfigurationTest.java
- eva-accession-deprecate/src/test/java/uk/ac/ebi/eva/accession/deprecate/configuration/DeprecateClusteredVariantsStepConfigurationTest.java
- eva-accession-deprecate/src/test/java/uk/ac/ebi/eva/accession/deprecate/configuration/DeprecateSubsetClusteredVariantsStepConfigurationTest.java
- eva-accession-deprecate/src/test/java/uk/ac/ebi/eva/accession/deprecate/io/DeprecableClusteredVariantsReaderTest.java
- eva-accession-deprecate/src/test/java/uk/ac/ebi/eva/accession/deprecate/io/DeprecationWriterTest.java
- eva-accession-deprecate/src/test/resources/test-data/dbsnpClusteredVariantEntity.json
- eva-accession-deprecate/src/test/resources/test-data/dbsnpClusteredVariantEntityDeclustered.json
- eva-accession-deprecate/src/test/resources/test-data/dbsnpSubmittedVariantEntity.json
- eva-accession-import/src/test/java/uk/ac/ebi/eva/accession/dbsnp/io/DbsnpVariantsWriterTest.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/configuration/readers/AccessionedVariantMongoReaderConfiguration.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/configuration/readers/MergedDeprecatedVariantMongoReaderConfiguration.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/configuration/readers/MergedVariantMongoReaderConfiguration.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/io/AccessionedVariantMongoReader.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/io/MergedDeprecatedVariantMongoReader.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/io/MergedVariantMongoReader.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/io/VariantMongoAggregationReader.java
- eva-accession-release/src/main/resources/application.properties
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/io/AccessionedVariantMongoReaderTest.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/io/MergedDeprecatedVariantMongoReaderTest.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/io/MergedVariantMongoReaderTest.java
make the eva-accession-deprecate and eva-accession-release assume that a Clustered Variant should be declustered if and only if it is present in dbsnpClusteredVariantEntityDeclustered and its RS ID is not used by any dbsnpSubmittedVariantEntity.
> EVA-1520 Adapt to deprecation bug in dbsnp import

- README.md
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/contig/ContigMapping.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/contig/ContigNaming.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/contig/ContigSynonyms.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/exceptions/NonIdenticalChromosomeAccessionsException.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/processors/ContigSynonymValidationProcessor.java
- eva-accession-pipeline/README.md
- eva-accession-pipeline/src/main/java/uk/ac/ebi/eva/accession/pipeline/configuration/AccessionWriterConfiguration.java
- eva-accession-pipeline/src/main/java/uk/ac/ebi/eva/accession/pipeline/configuration/VariantProcessorConfiguration.java
- eva-accession-pipeline/src/main/java/uk/ac/ebi/eva/accession/pipeline/configuration/jobs/steps/CheckSubsnpAccessionsStepConfiguration.java
- eva-accession-pipeline/src/main/java/uk/ac/ebi/eva/accession/pipeline/io/AccessionReportWriter.java
- eva-accession-pipeline/src/main/java/uk/ac/ebi/eva/accession/pipeline/parameters/InputParameters.java
- eva-accession-pipeline/src/main/java/uk/ac/ebi/eva/accession/pipeline/steps/processors/ContigReplacerProcessor.java
- eva-accession-pipeline/src/main/java/uk/ac/ebi/eva/accession/pipeline/steps/processors/ContigToGenbankReplacerProcessor.java
- eva-accession-pipeline/src/main/java/uk/ac/ebi/eva/accession/pipeline/steps/tasklets/reportCheck/ReportCheckTasklet.java
- eva-accession-pipeline/src/main/resources/application.properties
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/io/AccessionReportWriterTest.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/io/AccessionWriterTest.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/steps/processors/ContigToGenbankReplacerProcessorTest.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/steps/tasklets/reportCheck/ReportCheckTaskletTest.java
- eva-accession-pipeline/src/test/resources/accession-pipeline-interval-test.properties
- eva-accession-pipeline/src/test/resources/accession-pipeline-recover-test.properties
- eva-accession-pipeline/src/test/resources/accession-pipeline-test.properties
- eva-accession-pipeline/src/test/resources/input-files/assembly-report/assembly_report.txt
- eva-accession-pipeline/src/test/resources/input-files/assembly-report/mock_report.txt
- eva-accession-pipeline/src/test/resources/input-files/fasta/mock.fa
Using the original chromosomes is actually harder than I expected because we accession using the replaced contigs, and to match them with the original contigs we would need to pass both copies of each variant along the spring batch step. Currently, once we reach the writer to accession the variants, we only have the replaced contig.
Instead, this PR introduces a parameter `parameters.contigNaming` to write the report. It has these possible values:
```
public enum ContigNaming {
SEQUENCE_NAME,  // this is the same as chromosome names
ASSIGNED_MOLECULE,
INSDC,  // this is the same as GenBank
REFSEQ,
UCSC
}
```
and default value SEQUENCE_NAME.
The report check tasklet also replaces contigs from both the input and report VCFs into genbank (when possible) to be able to match the variants.
> EVA-1552 Use original chromosomes in accessioning VCF report

- eva-accession-release/src/main/resources/copy_release_to_ftp.sh
The first commit is a copy of the script similar to the one we had in the cluster but extracting some paths as parameters. The second includes MD5 checksums for the files, they are calculated and grouped in a single files `md5checksums.txt`
An example of the result with one species can be found in  `ftp://ftp.ebi.ac.uk/pub/databases/eva/rs_releases/test/` (this will be deleted once the ticket is done)
> EVA-1554 Include MD5 checksum files in FTP

- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/io/AccessionedVariantMongoReader.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/io/AccessionedVariantMongoReaderTest.java
- eva-accession-release/src/test/resources/test-data/dbsnpClusteredVariantEntity.json
- eva-accession-release/src/test/resources/test-data/dbsnpSubmittedVariantEntity.json
Given that the VCF release file for **current variants** include the alleles and those are only present in the submitted variants a join between the two collections is needed but given that the same RS ID can be mapped against multiple locations (chromosome and/or start position) we will need to filter the results with only the ones that match the location.
There will be an exceptional case with the ambiguous INDELs because dbSNP and the EVA treat them in different ways: dbSNP remove the context nucleotide before an INDEL while the EVA removes the rightmost bases
During the dbSNP import we re-normalize the submitted variants (which can imply modifying the start position) but the clustered variants are not renormalized.
This situation will be handled in this release pipeline by considering …
> EVA-1598 Filter variants for VCF release file of current variants

- eva-accession-import-dbsnp2/src/main/java/uk/ac/ebi/eva/accession/dbsnp2/configuration/ImportDbsnpJsonVariantsWriterConfiguration.java
- eva-accession-import-dbsnp2/src/main/java/uk/ac/ebi/eva/accession/dbsnp2/configuration/JsonNodeToClusteredVariantProcessorConfiguration.java
- eva-accession-import-dbsnp2/src/main/java/uk/ac/ebi/eva/accession/dbsnp2/io/JsonNodeToClusteredVariantProcessor.java
- eva-accession-import-dbsnp2/src/main/java/uk/ac/ebi/eva/accession/dbsnp2/parameters/InputParameters.java
- eva-accession-import-dbsnp2/src/main/resources/application.properties
- eva-accession-import-dbsnp2/src/test/java/uk/ac/ebi/eva/accession/dbsnp2/configuration/ImportDbsnpJsonVariantsJobConfigurationTest.java
- eva-accession-import-dbsnp2/src/test/java/uk/ac/ebi/eva/accession/dbsnp2/configuration/ImportDbsnpJsonVariantsStepConfigurationTest.java
- eva-accession-import-dbsnp2/src/test/java/uk/ac/ebi/eva/accession/dbsnp2/io/JsonNodeToClusteredVariantProcessorTest.java
- eva-accession-import-dbsnp2/src/test/java/uk/ac/ebi/eva/accession/dbsnp2/test/BatchTestConfiguration.java
- eva-accession-import-dbsnp2/src/test/resources/application.properties
- Add `@MongoConfiguration` from `eva-accession-core` to remove "_class" field from the persistence document
- Add new `refseqAssembly` and `genbankAssembly` as input parameters
- Add business logic to ignore variant if it's `assembly-accession` doesn't match `refseq-assembly`
- For processor test case, small change to ignore null variants
- Remove unused attributes/exceptions
- Mongo document: 
```
{
"_id": "7F4FBBB9CBBD9AEA24DCF86C023D620D6C8554A7",
"asm": "acsn1",
"tax": 9606,
"contig": "contig1",
"start": NumberLong(1),
"type": "SNV",
"accession": NumberLong(1),
"version": 1,
"createdDate": ISODate("2019-08-14T03:44:12.008Z")
}
```
- For testing purpose I modified Refseq accession to test the mismatch case. Result: No documents persist (as expected)
> Add ref seq input parameter, ignore variant on assembly accession mismatch 

- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/io/MergedVariantMongoReader.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/io/MergedVariantMongoReaderTest.java
- eva-accession-release/src/test/resources/test-data/dbsnpClusteredVariantOperationEntity.json
- eva-accession-release/src/test/resources/test-data/dbsnpSubmittedVariantOperationEntity.json
An exception should not be thrown if a clustered variant was merged but there are not operation for the submitted variants because they were declustered before. 
This happens because the decluster operations are created before the merge operations.
So we will have some situations where there is a merge operation but the merged clustered variant does not have any submitted variants associated because they all have been declustered (rs = null). Hence no update operation to indicate the merge is created for submitted variants.
> EVA-1639 Check ss ids declustered operations before throwing exeption

- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/configuration/processors/ReleaseProcessorConfiguration.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/configuration/writers/ContigWriterConfiguration.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/io/ContigWriter.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/io/VariantContextWriter.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/steps/processors/VariantToVariantContextProcessor.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/configuration/steps/ListActiveContigsStepConfigurationTest.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/configuration/steps/ListMergedContigsStepConfigurationTest.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/io/ContigWriterTest.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/io/VariantContextWriterTest.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/steps/processors/VariantToVariantContextProcessorTest.java
Sequence names are included in the contig file in order to write both the contig and the sequence name in the VCF headers of the RS Release.
Format should be:
```
##contig=<ID=chr01,Name="CM000001.3">
```
The `#CROM` Column of the VCF file now uses the sequence name
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
chr01   112     rs850979046     A       G       .       .       LOE;SID=BROAD_VGB_CANINE_PON_SNP_DISCOVERY;SS_VALIDATED=0;VC=SO:0001483
chr01   132     rs851217143     C       A       .       .       LOE;SID=BROAD_VGB_CANINE_PON_SNP_DISCOVERY;SS_VALIDATED=0;VC=SO:0001483
chr01   147     rs853028708     G       A       .       .       LOE;SID=BROAD_VGB_CANINE_PON_SNP_DISCOVERY;SS_VALIDATED=0;VC=SO:0001483
```
> EVA-1643 Switch sequence accessions and names 

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/exceptions/IllegalStartPositionException.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/exceptions/PositionOutsideOfContigException.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/io/FastaSequenceReader.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/policies/IllegalStartSkipPolicy.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/steps/processors/ContextNucleotideAdditionProcessor.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/policies/IllegalStartSkipPolicyTest.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/steps/processors/ContextNucleotideAdditionProcessorTest.java
This PR fixes a bug where variants in chromosomes that don't appear in the provided fasta, are reported as variants that are located past the end of its chromosome.
> EVA-1654 Assess the impact of variants with start position greater than end of chromosome

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/contig/ContigMapping.java
- eva-accession-core/src/test/java/uk/ac/ebi/eva/accession/core/contig/ContigMappingTest.java
- eva-accession-core/src/test/resources/input-files/assembly-report/GCA_000001635.8_Mus_musculus-grcm38.p6_assembly_report.txt
parsing asm report, overwrite duplicate genbank only if it's assembled-molecule.
What this achieves is ignoring scaffolds when translating from
genbank to other name (e.g. from genbank to sequence name), while
still having the mappings from different names to the same genbank.
> EVA-1666 Release the species other than EVA-1651

- eva-accession-import-dbsnp2/src/main/java/uk/ac/ebi/eva/accession/dbsnp2/configuration/ImportDbsnpJsonVariantsWriterConfiguration.java
- eva-accession-import-dbsnp2/src/main/java/uk/ac/ebi/eva/accession/dbsnp2/io/BzipLazyResource.java
- eva-accession-import-dbsnp2/src/main/java/uk/ac/ebi/eva/accession/dbsnp2/io/DbsnpJsonClusteredVariantsWriter.java
- eva-accession-import-dbsnp2/src/test/java/uk/ac/ebi/eva/accession/dbsnp2/io/DbsnpJsonClusteredVariantsWriterTest.java
While importing large BZ2 JSON files from ftp://ftp.ncbi.nih.gov/snp/latest_release/JSON/, I discovered that some of these were not being read entirely by the pipeline because the input stream did not permit concatenated BZ2 files. This PR fixes that issue by using [this specific constructor](https://commons.apache.org/proper/commons-compress/apidocs/org/apache/commons/compress/compressors/CompressorStreamFactory.html#createCompressorInputStream-java.lang.String-java.io.InputStream-boolean-) in Apache commons-compress library that allows for such files to be processed.
> EVA-1536 - Support concatenated BZ2 files and check for empty batches before write

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/configuration/MongoHumanConfiguration.java
- eva-accession-ws/src/test/java/uk/ac/ebi/eva/accession/ws/ClusteredVariantsRestControllerTest.java
The collection `DbsnpClusteredVariantOperationEntity` is present in human and non-human databases but in case of human an index is needed in the ` inactiveObjects.hashedMessage` field.
This is because when querying human variants by id fields we need to check the active collection but also the operations (variants in operations are also active for human)
> EVA-1760 Add index in clustered operations collection for human db only

- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/ClusteringMongoReader.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/BeanNames.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/io/ClusteringMongoReaderConfiguration.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/io/ClusteringWriterConfiguration.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/jobs/ClusteringFromMongoJobConfiguration.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/jobs/ClusteringFromVcfJobConfiguration.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/processors/ClusteringVariantProcessorConfiguration.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/steps/ClusteringFromMongoStepConfiguration.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/steps/ClusteringFromVcfStepConfiguration.java
- eva-accession-clustering/src/main/resources/application.properties
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/ClusteringMongoReaderTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/jobs/ClusteringVariantJobConfigurationTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/steps/ClusteringVariantStepConfigurationTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/test/configuration/BatchTestConfiguration.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/test/configuration/MongoTestConfiguration.java
- eva-accession-clustering/src/test/resources/test-data/submittedVariantEntityMongoReader.json
This PR includes:
- Mongo Reader implementation
- Configuration to have two different jobs: `CLUSTERING_FROM_VCF_JOB` and `CLUSTERING_FROM_MONGO_JOB` so the appropriate can be run depending on the data source
> EVA-1824 Mongo reader and Job for each data source

- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/IssueAccessionClusteringWriterTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/MergeAccessionClusteringWriterTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/ReuseAccessionClusteringWriterTest.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/model/dbsnp/DbsnpClusteredVariantOperationEntity.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/model/dbsnp/DbsnpSubmittedVariantOperationEntity.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/model/eva/ClusteredVariantOperationEntity.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/model/eva/SubmittedVariantOperationEntity.java
- pom.xml
Merge this PR after:
As mongo bulk operations don't fill the created date it has to be set manually in the operation entities constructor.
> EVA-2070 Add created date to operations

- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/ClusteringWriter.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/listeners/ClusteringCounts.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/listeners/ClusteringProgressListener.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/io/ClusteringWriterConfiguration.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/listeners/ListenersConfiguration.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/ClusteringWriterTestUtils.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/IssueAccessionClusteringWriterTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/MergeAccessionClusteringWriterTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/ReuseAccessionClusteringWriterTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/steps/ClusteringVariantStepConfigurationTest.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/service/nonhuman/ClusteredVariantAccessioningService.java
This PR includes
- Adding the clustering counts to the progress listener so we can log
- Clustered variants created (new accessions issued)
- Clustered variants updated (changed the RS accession due to a merge)
- Clustered variants merge operations
- Submitted variants updated (RS accession assigned, this means the SS was clustered)
- Submitted variants update operations
- Fix bug in getOrCreate method hardcoding `false` in the `newAccesion` field
- Tests for the clustering counts
This image shows the result after running the test for the step
> EVA-2042 Add summary metrics for the clustering pipeline

- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/batch/io/AssemblyNameRetriever.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/batch/io/VariantContextWriter.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/batch/io/AssemblyNameRetrieverTest.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/batch/io/VariantContextWriterTest.java
Note that the new code still complies with the idea of using the human readable URLs in the release VCFs, but using the API URLs to retrieve the assembly names.
> EVA-2112 Fix eva-accession-release tests

- eva-accession-clustering-automation/cluster_multiple_assemblies.py
- eva-accession-clustering-automation/create_clustering_properties.py
- Change mongo uri for mongo host+port in application.properties
- Fix the bsub command to detect the application.properties file
- Remove some withe spaces in the application.properties that were causing a parse error
- Include the vcf and project accessions params even when the source is mongo because the configuration require them
> EVA-2115 Fixes to clustering automation

- eva-accession-release-automation/run_release_in_embassy/copy_accessioning_collections_to_embassy.py
- eva-accession-release-automation/run_release_in_embassy/create_release_properties_file.py
- eva-accession-release-automation/run_release_in_embassy/merge_dbsnp_eva_release_files.py
- eva-accession-release-automation/run_release_in_embassy/release_common_utils.py
- eva-accession-release-automation/run_release_in_embassy/release_metadata.py
- eva-accession-release-automation/run_release_in_embassy/run_release_for_assembly.py
- eva-accession-release-automation/run_release_in_embassy/run_release_for_species.py
- eva-accession-release-automation/run_release_in_embassy/update_release_status_for_assembly.py
- eva-accession-release-automation/run_release_in_embassy/validate_release_vcf_files.py
* bcftools merge produces the following output -   weirdness with the contig names order in the header - ![Pasted image](https://dynalist.io/u/zzOMPDeaIl0oFskGwgBVkh5w)
* Ensure that the contigs line up in the merged file - addressed by adding a separate [function](https://github.com/sundarvenkata-EBI/eva-accession/commit/17466e7e7d589bdaa67a14ddd8f3114e2f3bd6eb#diff-00849c43c1cf839f5439988977aa7cbdR56) to merge headers
* Ensure that the internal details about the merge command does not appear in the merged file - addressed in [this commit](https://github.com/sundarvenkata-EBI/eva-accession/commit/17466e7e7d589bdaa67a14ddd8f3114e2f3bd6eb#diff-00849c43c1cf839f5439988977aa7cbdR114) by adding a **--no-version** switch to the merge commands
> EVA-2174 - Release automation fixes/enhancements

- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/ClusteringMongoReader.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/ClusteringWriter.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/ClusteringMongoReaderTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/MergeAccessionClusteringWriterTest.java
- When clustering we should take into account all variants, even if they are already clustered
- When a submitted variant is already clustered and is remapped (`remappedFrom` fields is not null) the pipeline checks if a merge is required
> EVA-2424 Remove filter that excludes clustered variants from reader

- eva-accession-clustering-automation/README.md
- eva-accession-clustering-automation/cluster_multiple_assemblies.py
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/runner/ClusteringCommandLineRunner.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/runner/ClusteringCommandLineRunnerTest.java
- eva-accession-core/pom.xml
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/runner/CommandLineRunnerUtils.java
- eva-accession-import-dbsnp2/src/main/java/uk/ac/ebi/eva/accession/dbsnp2/runner/DbsnpJsonImportVariantsJobLauncherCommandLineRunner.java
- eva-accession-import-dbsnp2/src/test/java/uk/ac/ebi/eva/accession/dbsnp2/runner/DbsnpJsonImportVariantsJobLauncherCommandLineRunnerTest.java
- eva-accession-import/src/main/java/uk/ac/ebi/eva/accession/dbsnp/runner/DbsnpImportVariantsJobLauncherCommandLineRunner.java
- eva-accession-pipeline/src/main/java/uk/ac/ebi/eva/accession/pipeline/runner/EvaAccessionJobLauncherCommandLineRunner.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/runner/EvaAccessionJobLauncherCommandLineRunnerTest.java
- eva-accession-release-automation/.gitignore
- eva-accession-release-automation/README.md
- eva-accession-release-automation/run_release_in_embassy/copy_accessioning_collections_to_embassy.py
- eva-accession-release-automation/run_release_in_embassy/create_release_properties_file.py
- eva-accession-release-automation/run_release_in_embassy/merge_dbsnp_eva_release_files.py
- eva-accession-release-automation/run_release_in_embassy/release_common_utils.py
- eva-accession-release-automation/run_release_in_embassy/release_metadata.py
- eva-accession-release-automation/run_release_in_embassy/requirements.txt
- eva-accession-release-automation/run_release_in_embassy/run_release_for_assembly.py
- eva-accession-release-automation/run_release_in_embassy/run_release_for_species.py
- eva-accession-release-automation/run_release_in_embassy/update_release_status_for_assembly.py
- eva-accession-release-automation/run_release_in_embassy/validate_release_vcf_files.py
- eva-accession-release-automation/run_release_in_embassy/validate_rs_release_files.py
- eva-accession-release-automation/setup.py
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/runner/AccessionReleaseJobLauncherCommandLineRunner.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/runner/AccessionReleaseJobLauncherCommandLineRunnerTest.java
- eva-remapping-get-source/src/main/java/uk/ac/ebi/eva/remapping/source/runner/AccessionRemappingJobLauncherCommandLineRunner.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/runner/IngestRemappedCommandLineRunner.java
Updates to the python automation scripts:
* Clustering automation works without modification, but I added a logs directory param for usability
* Release automation needs maven profile and release progress table name in config rather than hardcoded to run in internal
* Remove `job-repo-url` param as Spring Boot 2 upgrade should be done
* Added a skeletal readme to the release automation
Updates to java pipeline:
* Be more forgiving if no previous job execution found
> EVA-2463: Fixes from end-to-end testing

- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/BackPropagatedRSWriter.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/io/BackPropagatedRSWriterConfiguration.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/RemappedVariantsClusteringWriterTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/ReuseAccessionClusteringWriterTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/runner/ClusteringCommandLineRunnerTest.java
This PR is layered on top of [another PR](https://github.com/EBIvariation/eva-accession/pull/308). Therefore use [this link](https://github.com/sundarvenkata-EBI/eva-accession/compare/fix/overlapping_merges...sundarvenkata-EBI:fix/address_backprop_issues?expand=1) to view the actual differences.
This PR accomplishes the following:
* Address review comments regarding back-propagation from April and Tim. Links to the original review comments are provided inline in the PR.
* Update back-propagation writer to use back-propagation from the remapped assembly only if there is no suitable RS in the current assembly. See scenario [here](https://docs.google.com/spreadsheets/d/1KQLVCUy-vqXKgkCDt2czX6kuMfsjfCc9uBsS19MZ6dY/edit#rangeid=1618907977).
> EVA-2647 - Address RS back-propagation issues

- eva-accession-release-automation/run_release_in_embassy/create_release_properties_file.py
- eva-accession-release-automation/run_release_in_embassy/release_common_utils.py
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/batch/io/VariantMongoAggregationReader.java
- eva-accession-release/src/main/java/uk/ac/ebi/eva/accession/release/batch/io/active/AccessionedVariantMongoReader.java
- eva-accession-release/src/test/java/uk/ac/ebi/eva/accession/release/batch/io/active/AccessionedVariantMongoReaderTest.java
- eva-accession-release/src/test/resources/test-data/dbsnpSubmittedVariantEntity.json
This PR accomplishes two things:
* Ensure that [only the SS corresponding to the release assembly](https://github.com/EBIvariation/eva-accession/pull/309/commits/9d8295dc153cf6ff759b86a80b74be89b939a152) is chosen by the release pipeline
* Fix a [few issues in automation](https://github.com/EBIvariation/eva-accession/pull/309/commits/28f65b9829cbc5519dd8a8430419cf9405e929a2) that prevent release pipeline from running
> EVA-2652 - Fix release pipeline issues

- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/runner/ClusteringCommandLineRunnerTest.java
There was a [failed CI attempt](https://github.com/EBIvariation/eva-accession/actions/runs/2195431384/attempts/1) when merging the previous PR for this ticket. The failure was due to an accidental hash collision between evaSS1 and evaSS9 when creating original ASM records. This PR fixes that.
> EVA-2821 - Avoid accidental hash collision when creating original ASM SS records

- eva-accession-clustering-automation/clustering_automation/cluster_from_mongo.py
- eva-accession-clustering-automation/clustering_automation/create_clustering_progress_table.py
- eva-accession-clustering-automation/clustering_automation/update_clustering_status.py
- eva-accession-release-automation/include_mapping_weight_from_dbsnp/add_mapping_weight_attribute.py
- eva-accession-release-automation/include_mapping_weight_from_dbsnp/export_all_multimap_snps_from_dbsnp_dumps.py
- eva-accession-release-automation/include_mapping_weight_from_dbsnp/validate_mapping_weight_addition_to_mongo.py
- eva-accession-release-automation/publish_release_to_ftp/publish_release_files_to_ftp.py
Updating the changes made in this [commit](https://github.com/EBIvariation/eva-accession/commit/c6ade0a9e40acefae09e347b2180b720c116a99b) per [Nitin's suggestion](https://docs.google.com/document/d/1kisKFmtCg9rCGFOlb7gqf4j1GgHIGBcmhSVaRJGQPvw/edit?disco=AAAAaAzdBTA) to use production_processing profile.
> EVA-2823 - Update scripts to use production_processing profile

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/exceptions/MongoBulkWriteExceptionUtils.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/model/eva/SubmittedVariantEntity.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/model/eva/SubmittedVariantOperationEntity.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/batch/io/RemappedSubmittedVariantsWriter.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/batch/io/SubmittedVariantDiscardPolicy.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/batch/listeners/RemappingIngestCounts.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/batch/processors/VariantToSubmittedVariantEntityRemappedProcessor.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/configuration/BeanNames.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/configuration/CollectionNames.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/configuration/batch/io/IngestRemappedSubmittedVariantsWriterConfiguration.java
- eva-remapping-ingest/src/test/java/uk/ac/ebi/eva/remapping/ingest/batch/io/RemappedSubmittedVariantsWriterTest.java
- eva-remapping-ingest/src/test/java/uk/ac/ebi/eva/remapping/ingest/configuration/batch/jobs/IngestRemappedVariantsFromVcfJobConfigurationTest.java
- eva-remapping-ingest/src/test/java/uk/ac/ebi/eva/remapping/ingest/configuration/batch/steps/IngestRemappedFromVcfStepConfigurationTest.java
- pom.xml
Detect and resolve both duplicate hashes and duplicate SS in an assembly before ingesting remapped submitted variants.
> EVA-2937 - Detect duplicates when ingesting remapped variants

- eva-accession-release-automation/run_release_in_embassy/merge_dbsnp_eva_release_files.py
- eva-accession-release-automation/run_release_in_embassy/release_common_utils.py
- Ensure the final merge does not create multi allelic variant (request from Ensembl)
- Change the temp mongo database name to include the assembly to avoid overwriting the database when running per assembly process
> Merge and db name 

- eva-accession-clustering-automation/clustering_automation/create_clustering_properties.py
When running clustering for all studies we still need the parameters to be filled in.
> EVA-2991 - Add missing parameters for clustering

- eva-accession-release-automation/gather_clustering_counts/bash/count_rs_for_release.sh
- eva-accession-release-automation/gather_clustering_counts/bash/count_rs_for_release_for_txt.sh
- eva-accession-release-automation/gather_clustering_counts/bash/count_rs_for_release_unmapped.sh
- eva-accession-release-automation/gather_clustering_counts/gather_clustering_counts_from_mongo.py
- eva-accession-release-automation/gather_clustering_counts/gather_per_species_clustering_counts.py
- eva-accession-release-automation/gather_clustering_counts/requirements.txt
- eva-accession-release-automation/publish_release_to_ftp/publish_release_files_to_ftp.py
Scripts differences below
- count_rs_for_release.sh - [diff](https://www.diffchecker.com/OZVebcoC)
- count_rs_release_for_txt.sh - [diff](https://www.diffchecker.com/4SX2lHEk)
- count_rs_for_release_unmapped.sh - [diff](https://www.diffchecker.com/V4X70POd)
- gather_clustering_counts_from_mongo.py - [diff](https://www.diffchecker.com/wQ0aP21n)
- gather_per_species_clustering_counts.py - [diff](https://www.diffchecker.com/kGbNiu4F)
> EVA-3026 - Move clustering counts script from EVA-2770 and EVA-2750 to release automation

- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/batch/io/RemappedSubmittedVariantsWriter.java
- eva-remapping-ingest/src/main/java/uk/ac/ebi/eva/remapping/ingest/batch/listeners/RemappingIngestionProgressListener.java
- eva-remapping-ingest/src/test/java/uk/ac/ebi/eva/remapping/ingest/batch/io/RemappedSubmittedVariantsWriterTest.java
Added a couple tests to exemplify some slightly weird deduplication behaviour in the writer.  I believe it's actually correct and only applies to a situation where there are existing duplicate SS anyway, but combined with the lack of discard logging I think it could account for the counting discrepancy in the original ticket.  (I'll also create a new ticket for QC so we can continue to monitor the situation...)
> EVA-3124 - Log discards in remapping writer

- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/listeners/ListenersConfiguration.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/SSSplitWriterTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/jobs/ClusteringVariantJobConfigurationTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/steps/ClusteringVariantStepConfigurationTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/runner/ClusteringCommandLineRunnerTest.java
- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/configuration/ContigAliasConfiguration.java
- eva-accession-deprecate/src/main/java/uk/ac/ebi/eva/accession/deprecate/configuration/batch/listeners/ListenerConfiguration.java
- eva-accession-pipeline/src/main/java/uk/ac/ebi/eva/accession/pipeline/configuration/batch/listeners/ListenersConfiguration.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/runner/EvaAccessionJobLauncherCommandLineRunnerTest.java
- pom.xml
RestTemplate bean [for contig-alias introduced as part of EVA-3228](https://github.com/EBIvariation/eva-accession/blob/a027ce0ccb4765e509ef175c38c450837e70c73d/eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/configuration/ContigAliasConfiguration.java#L32) was chosen sporadically by Spring for autowiring [here](https://github.com/EBIvariation/eva-accession/blob/a027ce0ccb4765e509ef175c38c450837e70c73d/eva-accession-deprecate/src/main/java/uk/ac/ebi/eva/accession/deprecate/configuration/batch/listeners/ListenerConfiguration.java#L49) instead of the [RestTemplate with authentication](https://github.com/EBIvariation/eva-metrics/blob/eb0809edb57da83cad662d0e89504c53ff6b75fb/src/main/java/uk/ac/ebi/eva/metrics/configuration/MetricConfiguration.java#L20) meant for count-stats. …
> EVA-3267 - Explicitly name RestTemplate beans

- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/ClusteringWriter.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/RSMergeWriter.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/io/RSMergeAndSplitCandidatesReaderConfiguration.java
- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/jobs/ProcessRemappedVariantsWithRSJobConfiguration.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/RSMergeAndSplitCandidatesReaderTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/RSMergeWriterTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/IssueAccessionClusteringWriterTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/MergeAccessionClusteringWriterTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/RemappedVariantsClusteringWriterTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/batch/io/clustering_writer/ReuseAccessionClusteringWriterTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/configuration/batch/jobs/ClusteringVariantJobConfigurationTest.java
- eva-accession-clustering/src/test/java/uk/ac/ebi/eva/accession/clustering/runner/ClusteringCommandLineRunnerTest.java
Two major optimizations based on profiling:
* Use a [regex based ID search](https://github.com/EBIvariation/eva-accession/pull/393/files#diff-b6244e9907d2b0296d3a02a3fc6481f3fb8656821add15fea30f85a243ce3c59R608) to search for merge/split candidates
* Update [SVEs with the appropriate RS using ID lookups](https://github.com/EBIvariation/eva-accession/pull/393/files#diff-5dc442278e212785856f1b68bafbfa4a1e27c1c105b81adeda1ec9a84fa6c8deR459) instead of a query
> EVA-3164 - Low-hanging optimizations for clustering

- eva-accession-release-automation/gather_clustering_counts/bash/count_rs_for_all_files.sh
- eva-accession-release-automation/gather_clustering_counts/gather_release_counts.py
- eva-accession-release-automation/gather_clustering_counts/tests/test_gather_release_counts.py
- eva-accession-release-automation/publish_release_to_ftp/create_assembly_name_symlinks.py
- eva-accession-release-automation/publish_release_to_ftp/publish_release_files_to_ftp.py
`count_rs_for_all_files.sh`:
This PR adds a script that extract the rsids in release files and annotates each RS with the species/assembly/rs_type.
Then the annotation are aggregated per rsid and counted.
This allows for a generic count of rsid across species assemblies and type to be able to construct aggregate for each of these axes. 
`gather_release_counts.py`:
Determine the species and assembly that should be counted togethe, run `count_rs_for_all_files.sh` then parse and aggregate the results
> EVA-3409 Count rsid in release files 

- eva-remapping-get-source/src/main/java/uk/ac/ebi/eva/remapping/source/configuration/batch/io/VariantContextWriterConfiguration.java
- eva-remapping-get-source/src/main/java/uk/ac/ebi/eva/remapping/source/parameters/ReportPathResolver.java
- eva-remapping-get-source/src/test/java/uk/ac/ebi/eva/remapping/source/batch/io/VariantContextWriterTest.java
- eva-remapping-get-source/src/test/java/uk/ac/ebi/eva/remapping/source/configuration/batch/jobs/ExportSubmittedVariantsJobConfigurationTest.java
- eva-remapping-get-source/src/test/java/uk/ac/ebi/eva/remapping/source/runner/AccessionRemappingJobLauncherCommandLineRunnerTest.java
- eva-remapping-get-source/src/test/java/uk/ac/ebi/eva/remapping/source/runner/AccessionRemappingJobLauncherCommandLineRunnerWithProjectsTest.java
Add taxonomy in the file name of the VCF export to prevent file name collision when multiple taxonomies are exported
> EVA-3308 - Set the output file to contain the input taxonomy accession

- eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/batch/io/RSMergeWriter.java
Create new SPLIT candidates during merge that have the same accession as the one during the candidate detection.
> EVA-3544 - Fix SPLIT candidate accession

- eva-accession-release-automation/run_release_in_embassy/copy_accessioning_collections_to_embassy.py
- eva-accession-release-automation/run_release_in_embassy/run_release_for_species.py
One option is to just add labels
> EVA-3567 - Add basic labels to release accession

- eva-accession-release-automation/run_release_in_embassy/analyze_vcf_validation_results.py
- eva-accession-release-automation/run_release_in_embassy/copy_accessioning_collections_to_embassy.py
- eva-accession-release-automation/run_release_in_embassy/count_rs_ids_in_release_files.py
- eva-accession-release-automation/run_release_in_embassy/create_release_properties_file.py
- eva-accession-release-automation/run_release_in_embassy/initiate_release_status_for_assembly.py
- eva-accession-release-automation/run_release_in_embassy/merge_dbsnp_eva_release_files.py
- eva-accession-release-automation/run_release_in_embassy/release_common_utils.py
- eva-accession-release-automation/run_release_in_embassy/run_release_for_assembly.nf
- eva-accession-release-automation/run_release_in_embassy/run_release_for_assembly.py
- eva-accession-release-automation/run_release_in_embassy/run_release_for_species.py
- eva-accession-release-automation/run_release_in_embassy/sort_bgzip_index_release_files.py
- eva-accession-release-automation/run_release_in_embassy/update_release_status_for_assembly.py
- eva-accession-release-automation/run_release_in_embassy/update_sequence_names_to_ena.py
- eva-accession-release-automation/run_release_in_embassy/validate_release_vcf_files.py
- eva-accession-release-automation/run_release_in_embassy/validate_rs_release_files.py
- Add logging handlers so that each script can print our their logging statements
- Change the top level directory from config to not include the release
- Pass the assembly_release_folder to run_release_for_assembly.py
- Python interpreter is now taken form the currently used interpreter
> EVA-3586 - Multiple Fixes from running in production

- eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/configuration/nonhuman/MongoConfiguration.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/configuration/batch/jobs/CreateSeveralIntervalsOfSubsnpAccessionsJobConfigurationTest.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/configuration/batch/jobs/CreateSubsnpAccessionsJobConfigurationTest.java
- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/configuration/batch/steps/CreateSubsnpAccessionsStepConfigurationTest.java
- eva-accession-pipeline/src/test/resources/properties/accession-pipeline-interval-test.properties
Do this explicitly as apparently constructing it from the factory is not enough!
> EVA-3589: Set WriteConcern and ReadPreference for MongoTemplate

- eva-accession-release-automation/publish_release_to_ftp/publish_release_files_to_ftp.py
Only create a symlink in the by assembly directory if the corresponding by_species directory exists
> Check before creating by_assembly directories

- eva-accession-pipeline/src/test/java/uk/ac/ebi/eva/accession/pipeline/configuration/batch/steps/CreateSubsnpAccessionsStepConfigurationTest.java
- pom.xml
I have updated the test to throw an exception while trying to reserve a new block, forcing the code to retry. This is currently failing as it tries to use the same transaction once it succeeds after a few retries.
This test case should start passing once we pull in the changes done in accession commons to create a new transaction for every retry.
> EVA-3664 Update test to throw exception in transaction when saving new block
